'use client';

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RelayEnvironmentProvider } from 'react-relay';
import { initRelayEnvironment } from '@/RelayEnvironment';

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const relayEnvironment = initRelayEnvironment();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* AppRouterCacheProvider is required for the MUI Next.js App Router Cache. Added by Flexhire */}
        <AppRouterCacheProvider> 
        {/* RelayEnvironmentProvider is required for Relay to work. Added by Flexhire */}
          <RelayEnvironmentProvider environment={relayEnvironment}>
            {children}
          </RelayEnvironmentProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
